function fct_plot_cov_v(model,cov_scalaire_st,t,dt)
% Compute the correlation time of the Lagrangian velocity and plot the
% covariance of the Lagrangian velocity
%

tau = sum(cov_scalaire_st)*dt/cov_scalaire_st(1);
tau_day = tau/(3600*24);

% figure(20)
% plot(dt/(3600*24)*(-t:t), ...
%     [cov_scalaire_st(end:-1:2) cov_scalaire_st]);
% %         plot(dt/(3600*24)*(0:t),cov_scalaire_st);


        %% Plot
        
        width=5;
        height=3;
        figure20=figure(20);
        set(figure20,'Units','inches', ...
            'Position',[5 8 width height], ...
            'PaperPositionMode','auto');
        sym_cov = [cov_scalaire_st(end:-1:2) cov_scalaire_st];
        sym_t = dt/(3600*24)*(-t:t);
%         plot(sym_t, sym_cov);

        a = cov_scalaire_st;
        b = dt/(3600*24)*(0:t);
        plot(b,a);
        
        tau_str = num2str(tau_day);
        title(['$\tau_{V}=$' tau_str(1:4) ' days'],...
            'FontUnits','points',...
            'FontWeight','normal',...
            'interpreter','latex',...
            'FontSize',12,...
            'FontName','Times');
        set(gca,...
            'Units','normalized',...
            'FontUnits','points',...
            'FontWeight','normal',...
            'FontSize',11,...
            'FontName','Times')
% %         ylabel('$\| \nabla T \|^2_{L^2} - \| \nabla T_0 \|^2_{L^2} $',...
%         ylabel(['$\| \nabla T \|^2_{(\mathcal{L}^2 (\mathbb{R}^2))^2} ' ...
%                 '/ \| \nabla T_0 \|^2_{(\mathcal{L}^2 (\mathbb{R}^2))^2} $'],...
        ylabel('$Cov_{V}$',...
            'FontUnits','points',...
            'interpreter','latex',...
            'FontSize',11,...
            'FontName','Times')
        xlabel('$Time(days)$',...
            'interpreter','latex',...
            'FontUnits','points',...
            'FontWeight','normal',...
            'FontSize',11,...
            'FontName','Times')
%         ax = axis; ax(3) = 0.7; axis(ax);
        day = num2str(floor(t*dt/(3600*24)));
        eval( ['print -depsc ' model.folder.folder_simu ...
            '/cov_v_lag/' num2str(day) '.eps']);
        
        %% Plot
        
        width=5;
        height=3;
        figure21=figure(21);
        set(figure21,'Units','inches', ...
            'Position',[2 8 width height], ...
            'PaperPositionMode','auto');
        sym_cov = [cov_scalaire_st cov_scalaire_st(end-1:-1:2)];
%         sym_cov = sym_cov(1:end-1);
        sym_t = sym_t(1:end-1);
        dt_big = sym_t(2)-sym_t(1);
        N = length(sym_cov);
        P=N/2;
        freq = 1/N*[ 0:(P-1) (1-P):-1] ;
%         freq = 1/N*[ 0:(P-1) 0 (1-P):-1] ;
        freq=2*pi/dt_big*freq;
        ii_freq = (abs(freq) <=1);
        freq = freq(ii_freq);
        spectrum = real(fft(sym_cov));
        spectrum(P+1) = [];
        spectrum =spectrum(ii_freq);
%         residual = imag(fft(sym_cov))/real(fft(sym_cov));
%         residual = sum(residual.^2)
        plot(freq, spectrum,'o');
        title(['Spectrum of Lagrangian velocity'],...
            'FontUnits','points',...
            'FontWeight','normal',...
            'interpreter','latex',...
            'FontSize',12,...
            'FontName','Times');
        set(gca,...
            'Units','normalized',...
            'FontUnits','points',...
            'FontWeight','normal',...
            'FontSize',11,...
            'FontName','Times')
        ylabel('$\Gamma_{V}$',...
            'FontUnits','points',...
            'interpreter','latex',...
            'FontSize',11,...
            'FontName','Times')
        xlabel('$Frequency(days^{-1})$',...
            'interpreter','latex',...
            'FontUnits','points',...
            'FontWeight','normal',...
            'FontSize',11,...
            'FontName','Times')
%         ax = axis; ax(3) = 0.7; axis(ax);
        day = num2str(floor(t*dt/(3600*24)));
        eval( ['print -depsc ' model.folder.folder_simu ...
            '/spectrum_v_lag/' num2str(day) '.eps']);
        