init;

% figure;

a0_from_formula = 1;
k_m = 1;
k_M = 10;

beta = 0:0.1:2.9;

c_inf =  a0_from_formula * k_m^2 ./ (beta-3);
c_k_M = 1 - (beta.^2-1)/8 .* ...
    (repmat((k_M/k_m),[1 length(beta)])).^(3-beta);
c_k_M_from_formula_1 = c_inf .* c_k_M ;

c_k_M_from_formula_2 =  a0_from_formula * k_m^2 * ...
    ( log(k_M/k_m) - 3/4 );

beta = 3.1:0.1:6;

c_inf =  a0_from_formula * k_m^2 ./ (beta-3);
c_k_M = 1 - (beta.^2-1)/8 .* ...
    (repmat((k_M/k_m),[1 length(beta)])).^(3-beta);
c_k_M_from_formula_3 = c_inf .* c_k_M ;
    
c_k_M_from_formula = [ c_k_M_from_formula_1 c_k_M_from_formula_2 ...
    c_k_M_from_formula_3];


beta = 0:0.1:6;

X0= [0 0];
taille_police = 12;

% figure(5)
width = 4;
height = 3;
figure1=figure(1);
set(figure1,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
plot(beta,c_k_M_from_formula)
hold on;
plot(beta,zeros([1 length(beta)]),'r')
plot(beta,c_k_M_from_formula)
title('$c_{\kappa_M}$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$c_{\kappa_M}$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$\beta$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
drawnow
eval( 'print -depsc images/c_kM.eps');  



% figure;


beta_v = 01:0.01:4;
% beta_v = 0:0.01:4;
% % beta_v = 0:0.01:1;
% % beta_v = 0:0.01:6;
a0_from_formula = 1;
k_m = 1;
% % k_M_v = 10;
% k_M_v = 10.^(0.5:0.01:1.2);

k_M_v = 10.^(0:0.01:3);

i=0;j=0;
c_k_M_from_formula = nan(length(beta_v),length(k_M_v));
for beta=beta_v
    i=i+1;
    for k_M = k_M_v
        j=j+1;
        if beta ~= 3
            c_inf =  a0_from_formula * k_m^2 ./ (beta-3);
            c_k_M = 1 - (beta.^2-1)/8 .* ...
                (repmat((k_M/k_m),[1 length(beta)])).^(3-beta);
            c_k_M_from_formula(i,j) = c_inf .* c_k_M ;
        else
            c_k_M_from_formula(i,j) =  a0_from_formula * k_m^2 * ...
                ( log(k_M/k_m) - 3/4 );
        end
    end
    j=0;
end
i=0;
  
X0= [0 0];
taille_police = 12;

% figure(5)
width = 4;
height = 3;
figure2=figure(2);
set(figure2,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
% [beta_v,k_M_v]=ndgrid(beta_v,k_M_v);
contourf(beta_v,(k_M_v),(c_k_M_from_formula)');axis xy; 
% surf(beta_v,(k_M_v),(c_k_M_from_formula)');axis xy; 
set(gca,'YScale','log');
caxis(5e3*[-1 1]);
title('$c_{\kappa_M}$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\kappa_{M}$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$\beta$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
drawnow
eval( 'print -depsc images/c_kM_2D.eps');  



% shading flat

% figure;plot((c_k_M_from_formula))
