function w = fct_w_toy4(model)
% Create an incompressible velocity with circle streamlines and an angular
% velocity which is Gaussian function of the distance at the origin
%

model.odg_b=1e4;
model.k_inf_on_k1 = 4;
model.slope_b_ini = -8;
% model.slope_b_ini = -5;
phi = init_Spectrum(model);
w = gradient_ortho_perso(model.grid, phi);


%% Plots
% sqrt(mean(w(:).^2))
vort = vorticity_perso(model.grid, w);

width=3.5;
height=3;
X0 = [0 0];

% figure(2)
figure('Name','Angular velocity','NumberTitle','off','Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
x = model.grid.dX(1)*(0:model.grid.MX(1)-1);
% x=x-mean(x);
y = model.grid.dX(2)*(0:model.grid.MX(2)-1);
% y=y-mean(y);
imagesc(x,y,vort');
axis xy; axis equal;
% title('Velocity norm');
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('y(m)',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
xlabel('x(m)',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
colorbar
title('$Vorticity$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'interpreter','latex',...
    'FontName','Times')
axis([x(1) x(end) y(1) y(end)])

% Create the folders
fct_create_folder_plots(model)

eval( ['print -depsc ' model.folder.folder_simu '/vort_w.eps']);

