%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Simulate the deterministic and stochastic equation of the angle between
%%% tracer gradient and compressive strain direction
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


init;
%% Pameters

% % Physical parameters
% r_v = -2:0.1:2;
% % r_v = -2:0.1:2;
% alpha2_v = 10.^([-inf -3:0.1:2]);
% 
% s = [length(r_v) length(alpha2_v) ];
% 
% mean_zeta_v = nan(s);
% std_zeta_v = nan(s);
% m3_zeta_v = nan(s);
% m4_zeta_v = nan(s);
% 
% mean_sin_v = nan(s);
% mean_sin_v_modif = nan(s);
% std_sin_v = nan(s);
% m3_sin_v = nan(s);
% m4_sin_v = nan(s);
% 
% % mean_rho_v = nan(s);
% % std_rho_v = nan(s);
% % m3_rho_v = nan(s);
% % m4_rho_v = nan(s);
% 
% 
% for i=1:length(r_v)
%     r = r_v(i);
%     for j=1:length(alpha2_v)
%         alpha2 = alpha2_v(j);
%         %         r
%         
%         % Simulation parameters
%         T =  min ( [ 2/sqrt(abs(r^2-1)) abs(10/r) ] ) * 10;
%         T_statio = T;
%         T = 300*T;
%         dt = min (  [ min( [ 2/sqrt(abs(r^2-1)) abs(1/r) ] ) ...
%             (2*pi)^2/alpha2                       ] ) /100;
%         % dt=dt/10;
%         n_statio = ceil(T_statio/dt);
%         % T = min ( [ 2/sqrt(abs(r^2-1)) 10/r ] ) *5;
%         % T = 3e2 * 1;
%         % dt = 1e-1 * 1;
%         % T = 1e1 * alpha2;
%         % dt = 1e-1 * alpha2;
%         zeta_0 = 0.4;
%         rho_0 = 1;
%         
%         % Pre-treatement
%         time = 0:dt:T;
%         N =length(time);
%         alpha = sqrt(alpha2);
%         
%         % Sampling of noise
%         dBt = sqrt(dt) * randn(N,2);
%         
%         %% Time integration
%         zeta= nan(N,1);
%         ln_rho= nan(N,1);
%         zeta(1)=zeta_0;
%         ln_rho(1)=log(rho_0);
%         ln_rho_res(1)=log(rho_0);
%         for k_t=1:(N-1)
%             % for t_local = time(2:end)
%             zeta(k_t+1) = zeta(k_t) ...
%                 + ( r - cos( zeta(k_t) ) ) * dt ...
%                 + alpha * dBt(k_t,1) ;
%             ln_rho(k_t+1) = ln_rho(k_t) ...
%                 +  ( ( alpha2/12 - sin( zeta(k_t) ) ) * dt ...
%                 + alpha/sqrt(12) * dBt(k_t,2) );
%             ln_rho_res(k_t+1) = ln_rho_res(k_t) ...
%                 +  - sin( zeta(k_t))  * dt ;
%         end
%         zeta = mod(zeta+pi,2*pi)-pi;
%         
%         %% Remove transient
%         time(1:n_statio)=[];
%         ln_rho(1:n_statio)=[];
%         ln_rho_res(1:n_statio)=[];
%         zeta(1:n_statio)=[];
%         % zeta=sin(time);
%         N=N-n_statio;
%         % hN=floor(N/2);
%         % freq = 1/dt * 1/N * (0:(hN-1));
%         
%         %% To use the same code
%         zeta_end = zeta';
%         
%         %% Moments
%         mean_zeta = mean(zeta_end,2);
%         std_zeta = std(zeta_end,0,2);
%         center_norm_zeta = (zeta_end - mean_zeta)/std_zeta;
%         m3 = mean(center_norm_zeta.^3,2);
%         m4 = mean(center_norm_zeta.^4,2);
%         
%         m3(std_zeta<1e-3)=0;
%         m4(std_zeta<1e-3)=0;
%         m4(m4<3)=3;
%         m4 = log(m4-3);
%         
%         mean_zeta_v(i,j) = mean_zeta;
%         std_zeta_v(i,j) = std_zeta;
%         m3_zeta_v(i,j) = m3;
%         m4_zeta_v(i,j) = m4;
%         
%         mean_sin = mean(-sin(zeta_end),2);
%         std_sin = std(-sin(zeta_end),0,2);
%         center_norm_sin = (-sin(zeta_end) - mean_sin)/std_sin;
%         m3 = mean(center_norm_sin.^3,2);
%         m4 = mean(center_norm_sin.^4,2);
%         
%         m3(std_sin<1e-3)=0;
%         m4(std_sin<1e-3)=0;
%         m4(m4<3)=3;
%         m4 = log(m4-3);
%         
%         mean_sin_v(i,j) = mean_sin;
%         mean_sin_v_modif(i,j) = mean_sin+alpha2/12;
%         std_sin_v(i,j) = std_sin;
%         m3_sin_v(i,j) = m3;
%         m4_sin_v(i,j) = m4;
%         
%         
%     end
% end
% 
% save('save_r_alpha/average_time');

%% PLots

load('save_r_alpha/average_time');

alpha2_v(1)=10^(-3.5);
alpha2_v = log(alpha2_v)/log(10);

X0= [0 0];
taille_police = 12;

% figure(5)
width = 8;
height = 5;
figure1=figure(1);
set(figure1,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
subplot(2,2,1)
imagesc(r_v,alpha2_v,mean_zeta_v');
axis xy;colorbar;
caxis([-pi 0]);
% caxis([-pi pi]);
title('Mean $\zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,2)
imagesc(r_v,alpha2_v,std_zeta_v');
axis xy;colorbar;
% caxis([-pi pi]);
title('Std $\zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,3)
imagesc(r_v,alpha2_v,m3_zeta_v');axis xy;colorbar;
cax=caxis;cax(1)=0;caxis(cax);
title('Skewness $\zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,4)
imagesc(r_v,alpha2_v,m4_zeta_v');axis xy;colorbar;
title('Excess kurtosis $\zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
drawnow
eval( 'print -depsc save_r_alpha/zeta_average_time.eps');  

% figure(6)
% subplot(2,2,1)
% imagesc(r_v,alpha2_v,mean_sin_v');
% axis xy;colorbar;caxis([-1 1]);
% subplot(2,2,2)
% imagesc(r_v,alpha2_v,std_sin_v');
% axis xy;colorbar;caxis([-1 1]);
% subplot(2,2,3)
% imagesc(r_v,alpha2_v,m3_sin_v');axis xy;colorbar;
% subplot(2,2,4)
% imagesc(r_v,alpha2_v,m4_sin_v');axis xy;colorbar;


% figure(7)
width = 8;
height = 5;
figure2=figure(2);
set(figure2,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
subplot(2,2,1)
imagesc(r_v,alpha2_v,mean_sin_v_modif');
axis xy;colorbar;
caxis([0 1]);
% caxis([-1 1]);
title('Mean $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,2)
imagesc(r_v,alpha2_v,std_sin_v');
axis xy;colorbar;
% caxis([0 1]);
title('Std $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,3)
imagesc(r_v,alpha2_v,m3_sin_v');axis xy;colorbar
cax=caxis;cax(2)=1;caxis(cax);
title('Skewness $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,4)
imagesc(r_v,alpha2_v,m4_sin_v');axis xy;colorbar;
title('Excess kurtosis $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
drawnow
eval( 'print -depsc save_r_alpha/growth_rate_average_time.eps');  



