%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Simulate the deterministic and stochastic equation of the angle between
%%% tracer gradient and compressive strain direction
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


init;
%% PLots

load('save_r_alpha/average_time');

alpha2_v(1)=10^(-3.5);
alpha2_v = log(alpha2_v)/log(10);

X0= [0 0];
taille_police = 12;

% figure(5)
width = 8;
height = 5;
figure1=figure(1);
set(figure1,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
subplot(2,2,1)
imagesc(r_v,alpha2_v,mean_zeta_v');
axis xy;colorbar;caxis([-pi pi]);
title('$Mean \zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,2)
imagesc(r_v,alpha2_v,std_zeta_v');
axis xy;colorbar;
% caxis([-pi pi]);
title('Std $\zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,3)
imagesc(r_v,alpha2_v,m3_zeta_v');axis xy;colorbar;
title('Skewness $\zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,4)
imagesc(r_v,alpha2_v,m4_zeta_v');axis xy;colorbar;
title('Excess kurtosis $\zeta$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
drawnow
eval( 'print -depsc save_r_alpha/zeta_average_time.eps');  

% figure(6)
% subplot(2,2,1)
% imagesc(r_v,alpha2_v,mean_sin_v');
% axis xy;colorbar;caxis([-1 1]);
% subplot(2,2,2)
% imagesc(r_v,alpha2_v,std_sin_v');
% axis xy;colorbar;caxis([-1 1]);
% subplot(2,2,3)
% imagesc(r_v,alpha2_v,m3_sin_v');axis xy;colorbar;
% subplot(2,2,4)
% imagesc(r_v,alpha2_v,m4_sin_v');axis xy;colorbar;

%% Growth rate

% figure(7)
width = 8;
height = 5;
figure2=figure(2);
set(figure2,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
subplot(2,2,1)
imagesc(r_v,alpha2_v,mean_sin_v_modif');
axis xy;colorbar;
caxis([0 1]);
% caxis([-1 1]);
title('Mean $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,2)
imagesc(r_v,alpha2_v,std_sin_v');
axis xy;colorbar;
% caxis([0 1]);
title('Std $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,3)
imagesc(r_v,alpha2_v,m3_sin_v');axis xy;colorbar;
title('Skewness $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
subplot(2,2,4)
imagesc(r_v,alpha2_v,m4_sin_v');axis xy;colorbar;
title('Excess kurtosis $\frac{\alpha^2}{12} - \sin(\zeta)$',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
drawnow
eval( 'print -depsc save_r_alpha/growth_rate_average_time.eps');  

%% Partition

[r_v_grid,alpha2_v_grid] = ndgrid(r_v,alpha2_v);

m_sin_zeta = mean_sin_v_modif - 10.^(alpha2_v_grid)/12;

state = fct_choose_states(mean_sin_v_modif,m4_sin_v,alpha2_v_grid);
% state = 1/5 * state;

% inf_hyp = 0.5;
% inf_extrem = 0.1;
% % inf_sto_hyp = 0.5;
% sup_ell = 0.01;
% 
% state = 0 * ...
%     ( mean_sin_v_modif < sup_ell ) ...
%     ... % deterministic ellipticity
%       + 2 * ...
%       ( mean_sin_v_modif >= sup_ell & mean_sin_v_modif <= inf_hyp  ) ...
%       ... % weak stochastic hyperbolity
%       + 3 * ...
%       ( mean_sin_v_modif >= inf_hyp  & m4_sin_v < inf_extrem & 10.^(alpha2_v_grid)/12 <= m_sin_zeta) ...
%       ... % deterministic hyperbolicity
%       + 4 * ...
%       ( mean_sin_v_modif >= inf_hyp  & m4_sin_v >= inf_extrem & 10.^(alpha2_v_grid)/12 <= m_sin_zeta) ...
%       ... % deterministic hyperbolicity with stochastic elliptic bursts
%       + 5 * ...
%       (  mean_sin_v_modif <= inf_hyp  & m4_sin_v >= inf_extrem ) ...
%       ... % weaker hyperbolity due to stochastic elliptic bursts
%       + 6 * ...
%       ( mean_sin_v_modif >= inf_hyp  & 10.^(alpha2_v_grid)/12 > m_sin_zeta); 
%           % stochastic hyperbolicity

l_r =length(r_v);
l_r_usefull = (l_r-1)/2 +1;
v_r_usefull = l_r_usefull:l_r;

% figure(7)
width = 4;
height = 4;
% height = 2.5;
% width = 8;
% height = 5;
figure3=figure(3);
set(figure3,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
% subplot(2,2,1)
% contourf(r_v,alpha2_v,state');
imagesc(r_v(v_r_usefull),alpha2_v,state(v_r_usefull,:)');
axis xy;colorbar;
% caxis([0 1]);
% caxis([-1 1]);
title('States',...
    'Interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
ylabel('$\log\ (\alpha^2)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$r$',...
    'interpreter','latex',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
drawnow
eval( 'print -depsc save_r_alpha/States.eps');  
eval( 'print -depsc save_r_alpha/States.png');  
